using Microsoft.Extensions.AI;

namespace SemanticStart.Core.Embeddings;

/// <summary>
/// Bridges the Microsoft.Extensions.AI generator contract to the float-array representation used
/// by the local index. Providers must expose <see cref="EmbeddingGeneratorMetadata"/> so an index
/// can reject vectors generated by a different model or with different dimensions.
/// </summary>
public static class EmbeddingGeneratorExtensions
{
    public static EmbeddingGeneratorMetadata GetRequiredMetadata(
        this IEmbeddingGenerator<string, Embedding<float>> generator)
    {
        ArgumentNullException.ThrowIfNull(generator);

        var metadata = generator.GetService(typeof(EmbeddingGeneratorMetadata), serviceKey: null)
            as EmbeddingGeneratorMetadata;
        if (metadata is null
            || string.IsNullOrWhiteSpace(metadata.DefaultModelId)
            || metadata.DefaultModelDimensions is not > 0)
        {
            throw new InvalidOperationException(
                $"Embedding generator '{generator.GetType().FullName}' must expose an " +
                "EmbeddingGeneratorMetadata service with a model ID and positive dimensions.");
        }

        return metadata;
    }

    public static async Task<IReadOnlyList<float[]>> GenerateVectorsAsync(
        this IEmbeddingGenerator<string, Embedding<float>> generator,
        IReadOnlyList<string> texts,
        int expectedDimensions,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(generator);
        ArgumentNullException.ThrowIfNull(texts);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(expectedDimensions);

        if (texts.Count == 0)
            return Array.Empty<float[]>();

        var generated = await generator
            .GenerateAsync(texts, cancellationToken: cancellationToken)
            .ConfigureAwait(false);

        if (generated.Count != texts.Count)
        {
            throw new InvalidOperationException(
                $"Embedding generator returned {generated.Count} vectors for {texts.Count} inputs.");
        }

        var vectors = new float[generated.Count][];
        for (var i = 0; i < generated.Count; i++)
        {
            var vector = generated[i].Vector;
            if (vector.Length != expectedDimensions)
            {
                throw new InvalidOperationException(
                    $"Embedding generator returned {vector.Length} dimensions; expected {expectedDimensions}.");
            }

            vectors[i] = vector.ToArray();
        }

        return vectors;
    }
}
